title: Peter A Tkatchenko
logo: /assets/img/peter_tkatchenko_china_visa_photo_33x48mm.jpg
description: Aspiring economist, socially-conscious philosophical thought appreciator
show_downloads: true
theme: jekyll-theme-minimal
